### ISSUE TITLE
Bug: `None` in error message on windows when the command to run cannot be found

### ISSUE THREAD

**Issue by ddneilson** [OpenJobDescription/openjd-sessions-for-python#128]
### Expected Behaviour

```
Thu Apr 25 13:14:56 2024        ----------------------------------------------
Thu Apr 25 13:14:56 2024        Phase: Running action
Thu Apr 25 13:14:56 2024        ----------------------------------------------
Thu Apr 25 13:14:56 2024        Running command echo "Hello World"
Thu Apr 25 13:14:56 2024        <some sort of message about 'echo' not being a program available on the PATH>
```

### Current Behaviour

```
Thu Apr 25 13:14:56 2024        ----------------------------------------------
Thu Apr 25 13:14:56 2024        Phase: Running action
Thu Apr 25 13:14:56 2024        ----------------------------------------------
Thu Apr 25 13:14:56 2024        Running command None "Hello World"
Thu Apr 25 13:14:56 2024        Process failed to start: [WinError 2] The system cannot find the file specified
```

### Reproduction Steps

Run this template via the CLI on Windows:
```
specificationVersion: "jobtemplate-2023-09"
name: Hello World
steps:
- name: Hello World Step
  script:
    actions:
      onRun:
        command: "echo"
        args:
        - "Hello World"
```

### Code Snippet

N/A
